services:
  db:
    image: postgres:15-alpine
    container_name: fitness-db
    environment:
      POSTGRES_DB: fitnessdb
      POSTGRES_USER: fitnessuser
      POSTGRES_PASSWORD: fitnesspassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
