spring.application.name=FitnessHelper
spring.datasource.url=jdbc:postgresql://localhost:5433/fitnessdb
spring.datasource.username=fitnessuser
spring.datasource.password=fitnesspassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
